name: assignment1
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: change working directory
        run: cd ./04PracticeProject
      - name: install dependencies
        run: npm ci
        working-directory: ./04PracticeProject
      - name: lint cpde
        run: npm lint
        working-directory: ./04PracticeProject
      - name: run tests
        run: npm test
        working-directory: ./04PracticeProject
      - name: build project
        run: npm run build
        working-directory: ./04PracticeProject
      - name: deploy
        run: echo "Deploying"


        
